server:
  port: 80
spring:
  application:
#    应用名称
    name: reggie
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/reggie?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: 123456
  data:
    redis:
      host: localhost
      port: 6379
      #password: 123456
      database: 1
      jedis:
        pool:
          max-idle: 8
          min-idle: 0
          max-active: 10
          max-wait: 10ms
  cache:
    redis:
      time-to-live: 1800000 #设置过期时间
mybatis-plus:
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID

reggie:
  upload-file: F:\\img\