server:
  port: 80
spring:
  application:
#    应用名称
    name: reggie
  shardingsphere:
    datasource:
      #设置多个数据库
      names: master,slave
      # 主库
      master:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://192.168.164.100:3306/reggie?useUnicode=true&characterEncoding=UTF-8&useSSL=false
        username: root
        password: root
      # 从库
      slave:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://192.168.164.131:3306/reggie?useUnicode=true&characterEncoding=UTF-8&useSSL=false
        username: root
        password: root
    masterslave:
      # 查询机制
      load-balance-algorithm-type: round_robin
      # 数据源名称
      name: dataSource
      # 设置主库
      master-data-source-name: master
      # 设置从库 ，可以多个用，分开
      slave-data-source-names: slave
    props:
      sql:
        show: true #开启SQL显示，默认false
  main:
    allow-bean-definition-overriding: true
  data:
    redis:
      host: localhost
      port: 6379
      #password: 123456
      database: 1
      jedis:
        pool:
          max-idle: 8
          min-idle: 0
          max-active: 10
          max-wait: 10ms
  cache:
    redis:
      time-to-live: 1800000 #设置过期时间
mybatis-plus:
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID

reggie:
  upload-file: F:\\img\